pilot:
  autoscaleEnabled: true
  autoscaleMin: 2
  autoscaleMax: 3
  rollingMaxUnavailable: 25%
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - istiod
            topologyKey: kubernetes.io/hostname