apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: centrifugo
  namespace: centrifugo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: centrifugo
  endpoints:
  - port: 9000
    interval: 30s