---
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'centrifugo'
        static_configs:
          - targets: ['centrifugo.centrifugo.svc.cluster.local:8000']
prometheus-node-exporter:
  enabled: false