name: Deploy Apigee API from OpenAPI Spec

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

env:
  APIGEE_ENV: dev
  TF_HTTP_PASSWORD: ${{ secrets.GH_PAT_TOKEN }}

jobs:
  deploy-oas:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.PROD_WIF_POOL }}
          service_account: ${{ secrets.PROD_SA_EMAIL }}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use the latest Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      
      - name: Install Apigee CLI
        run: |
          curl -L https://raw.githubusercontent.com/apigee/apigeecli/main/downloadLatest.sh | sh -

      - name: Prepare API Bundle
        run: |
          export PATH=$PATH:$HOME/.apigeecli/bin 
          python3 scripts/prepare_bundle.py \
            --apigee_org ${{ secrets.APIGEE_ORG }} \
            --api_name "$APIGEE_PROXY_NAME" \
            --api_base_path "$APIGEE_PROXY_BASEPATH" \
            --oas_file_location . \
            --oas_file_name httpbin.yaml
        env:
          APIGEE_PROXY_NAME: oasapi1
          APIGEE_PROXY_BASEPATH: /oasapi1
      
      - name: Prepare API Bundle with override SF
        run: |
          export PATH=$PATH:$HOME/.apigeecli/bin 
          python3 scripts/prepare_bundle.py \
            --apigee_org ${{ secrets.APIGEE_ORG }} \
            --api_name "$APIGEE_PROXY_NAME" \
            --api_base_path "$APIGEE_PROXY_BASEPATH" \
            --oas_file_location . \
            --oas_file_name httpbin.yaml \
            --override_flow_name getUsersGroups \
            --override_sf_name SF-spitfire-pre
        env:
            APIGEE_PROXY_NAME: oasapi2
            APIGEE_PROXY_BASEPATH: /oasapi2
  
      - uses: hashicorp/setup-terraform@v3

      - name: Run terraform
        run: |
          cd terraform
          terraform init
          terraform plan \
            -var "apigee_org=${{ secrets.APIGEE_ORG }}" \
            -var "apigee_env=$APIGEE_ENV" \
            -var 'api_proxies=["oasapi1", "oasapi2"]' \
            -var "api_proxy_path=${{ github.workspace }}" \
            -var "shared_flow_path=${{ github.workspace }}/sharedflows" \
            -var "openid_discovery_endpoint=${{ secrets.APIGEE_TARGET_SERVER }}" \
            -var 'target_servers={
                    "user-manager-user-query" = {
                      host        = "${{ secrets.APIGEE_TARGET_SERVER }}"
                      port        = 443
                      protocol    = "HTTP"
                      ssl_enabled = true
                    },
                    "user-manager-user-create" = {
                      host        = "${{ secrets.APIGEE_TARGET_SERVER }}m"
                      port        = 443
                      protocol    = "HTTP"
                      ssl_enabled = true
                    },
                    "auth-manager-token-introspect" = {
                      host        = "${{ secrets.APIGEE_TARGET_SERVER }}"
                      port        = 443
                      protocol    = "HTTP"
                      ssl_enabled = true
                    }
                  }'
          terraform apply \
            -auto-approve \
            -var "apigee_org=${{ secrets.APIGEE_ORG }}" \
            -var "apigee_env=$APIGEE_ENV" \
            -var 'api_proxies=["oasapi1", "oasapi2"]' \
            -var "api_proxy_path=${{ github.workspace }}" \
            -var "shared_flow_path=${{ github.workspace }}/sharedflows" \
            -var "openid_discovery_endpoint=${{ secrets.APIGEE_TARGET_SERVER }}" \
            -var 'target_servers={
                    "user-manager-user-query" = {
                      host        = "${{ secrets.APIGEE_TARGET_SERVER }}"
                      port        = 443
                      protocol    = "HTTP"
                      ssl_enabled = true
                    },
                    "user-manager-user-create" = {
                      host        = "${{ secrets.APIGEE_TARGET_SERVER }}m"
                      port        = 443
                      protocol    = "HTTP"
                      ssl_enabled = true
                    },
                    "auth-manager-token-introspect" = {
                      host        = "${{ secrets.APIGEE_TARGET_SERVER }}"
                      port        = 443
                      protocol    = "HTTP"
                      ssl_enabled = true
                    }
                  }'
