name: Prepare API Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  prepare-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use the latest Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Prepare API Bundle
        run: |
          python3 scripts/prepare_bundle.py \
            --apigee_org ${{ secrets.APIGEE_ORG }} \
            --api_name newapi \
            --api_base_path /newapi \
            --oas_file_location . \
            --oas_file_name httpbin.yaml
